name: Build Prisma Studio Docker image (multi-arch)

on:
  push:
    branches: main
  workflow_dispatch: 

  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build & Publish to DockerHub
        run: |
          docker buildx build \
            --tag tadesf/prisma-studio:latest \
            --platform linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm64/v8,linux/amd64 . --push
